### ISSUE TITLE
create release tag

### ISSUE THREAD

**Issue by ncopa** [yetanothergeek/xctrl#3]
Hi, would it be possible to create a release tag?

It would be very helpful for downstream packagers.

Thanks!

**Comment by yetanothergeek** [comment]
Hi, ncopa -

I haven't used the "release" feature on github, but it's been my experience so far that some things here are fairly easy to do, and virtually impossible to undo.

So I'm hoping to get this right the first time...

The releases on the old googlecode site were:
* xctrl-2010-10-26.tar.gz
* xctrl-2013-06-19.tar.gz
* xctrl-2013-06-20.tar.gz


So, If I create new tags in the github repo something like:
* git tag 2010-10-26 d922fcf
* git tag 2013-06-19 fcfd525
* git tag 2013-06-20 a5fe060
* git tag 2015-04-09 0c0ed93


Then I can go to the "Creating Releases" page and create a release for each version number:
* 2010-10-26
* 2013-06-19
* 2013-06-20
* 2015-04-09

Will that be OK on your end?

**Comment by ncopa** [comment]
would be ok. I would prefer dots instead of dashes (2015.04.09), but its not a big deal

thanks!

**Comment by yetanothergeek** [comment]
Sorry for the slow response, I ran into some questions about the "Creating Releases" page and it took a while for the github staff to beat some sense into my head.

Anyway, I created tags for the previous googlecode releases, but I only created an official  "release" tag for the latest github-only version. All the tags use dots instead of dashes as you suggested. Let me know if you need anything else.

Thanks for the nudge!

**Comment by ncopa** [comment]
Simple tags are perfectly ok too.

Thanks!
